services:
  postgres:
    image: 'bitnami/postgresql'
    container_name: 'ecommerce'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=ecommercedb
